services:
  postgres:
    image: postgres:16-alpine
    container_name: sensor-pg2
    environment:
      POSTGRES_DB: sensor
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    volumes:
      - sensor_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d sensor"]
      interval: 5s
      timeout: 3s
      retries: 10

  sensor-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sensor-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - APP_PROFILE=prod
      - SENSORS_FILE=/app/config/sensors.json
    volumes:
      - ./src/main/resources/sensors.json:/app/config/sensors.json:ro
    restart: unless-stopped

volumes:
  sensor_pgdata: